config:
  delay: 5
  loop: true
  loop_limit: 10

keys:
- 'a': # Key to be pressed/released
   #type: x is optional, defaults to instant press and release, or user can set it to press
    delta: 0 # Time to wait before key press in seconds
- 'a':
    type: down # Down for key press down
    delta: 2
- 'a':
    type: up # Up for key release
    delta: 2
- 'a':
    type: press
    delta: 2